// <auto-generated />
namespace MIS320_Team7Project_Fall2016.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GoodDbMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GoodDbMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201611151917233_GoodDbMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
